name: Create Docker Images

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./ViennaTools
          platforms: linux/amd64,linux/arm64
          push: true
          tags: yozoon/viennatools:latest
          cache-from: type=registry,ref=yozoon/viennatools:buildcache
          cache-to: type=registry,ref=yozoon/viennatools:buildcache,mode=max
          build-args: |
            squash=true
